Api后台管理+swagger-ui
myloveGy/yii2-ace-admin pull request #5
Opened 2018-01-23 10:24 UTC by wooliaolin

1.添加composerrepositories；
2.添加api后台管理模块;

2018-01-23 10:25 UTC, wooliaolin commented
1.添加composerrepositories；
2.添加api后台管理模块;

2018-01-23 10:47 UTC, myloveGy commented on backend/controllers/ApiController.php
> +    public function actionSwagger()
如果是json 数据返回，强烈建议使用return $this->asJson(); 返回数据，不要手动去拼写json
```
$data = $this->getQuery(['version' => 'v1'])->all();
        $arrApi = [];
        foreach ($data as $value) {
            $arrApi[$value['url']][$value['method']] = [
                'tags' => explode(',', $value['tags']), // 填写的时候可以,号分隔多个
                'summary' => $value['summary'],
                'description' => $value['description'],
                'produces' => $value['produces'],
                'parameters' => $value['parameters'],
                'responses' => $value['responses'],
            ];
        }

        return $this->asJson([
            'swagger' => '2.0',
            'info' => [
                'title' => 'ApiDoc',
                'version' => 'v1',
            ],
            'paths' => $arrApi,
        ]);
```

2018-01-23 10:51 UTC, myloveGy commented on backend/controllers/Controller.php
> +            if (Yii::$app->user->id!=1){
不要为管理员开这个开口，只要你添加了对应的权限，默认会给管理员的！
``` 
if (Yii::$app->user->id != 1) 去掉

2018-01-23 11:34 UTC, myloveGy commented on backend/models/Api.php
> + */
这个地方不要继承AdminModel 因为你表中没有 created_id 和 updated_id 字段，继承\yii\db\ActiveRecord 就好了，要自动维护 created_at 和 update_at 的话，添加行为就好了 
```
/**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }
```

2018-01-23 11:53 UTC, myloveGy requested changes
很感谢你能和我一起开发！但我发现几个小问题，希望能修改下，我都有备注说明，还有就是：
1. 希望代码风格保持PSR-2(使用phpstorm的 ctrl + alt + l)
2. 希望把api表的数据库迁移文件加上去(表字段的备注都尽量写上)

2018-01-24 02:21 UTC, wooliaolin commented on backend/controllers/ApiController.php
> +    public function actionSwagger()
嗯，这块是我昨天做的。还不是很完善昨晚到家我才想到应该再优化一下提交。添加api接口的地方还不是很方便，然后返回json的时候应该按你说的return $this->asJson(); 操作才对。

2018-01-30 01:52 UTC, merged